config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  resources :dashboard
  resources :categories do
    resources :artists   do
      resources :questions do
        resources :responses do
        resources :options
      end
      end
    end
  end

  get '/categories' => 'categories#index'
  get '/artists' => 'artists#index'
  get 'index2' => 'home#index'
  get 'index23' => 'artists#index'
  post '/responses' => 'artists#create_response'
  root :to => 'home#index'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  rss_url     :string
#

class Artist < ActiveRecord::Base
	belongs_to :category
	has_many :questions, :dependent => :destroy
	has_many :facts
end

app/models/category.rb
	# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :artists
	has_many :questions, through: :artist
	has_many :facts, through: :artist
end

app/models/fact.rb
# == Schema Information
#
# Table name: facts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Fact < ActiveRecord::Base
	belongs_to :artist
end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  text        :string
#  correct     :boolean
#  question_id :integer
#

class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Player < ActiveRecord::Base
	has_many :responses
	has_many :player_questions
	has_many :questions, through: :player_questions
	# has_many :points

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         def points
          # refactor into single query without map

          # go to responses datatable, return me responses where 
          ## the player is the same player this method is being used on
          # => [<response><response>]
          Response.where(player: self).map{ |response|
            if response.option.correct
              response
            else
              nil
            end
          }.compact.count
          # => [nil, <response>, <response>, nil, <response>].compact
          # => [<response>, <response>, <response>].count
          # => 3
         end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#  text       :string
#  youtube_id :string
#

class Question < ActiveRecord::Base
	has_many :options, :dependent => :destroy
	belongs_to :artist
	belongs_to :category
	has_many :responses, through: :options
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  player_id  :integer
#  option_id  :integer
#

class Response < ActiveRecord::Base
	belongs_to :player
	belongs_to :option
	belongs_to :question
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@artist = Artist.new
	end

	def index
		@artist = Artist.all
	end

	def index23
	end

	def show
		@artist = Artist.find(params[:id])
		if current_player
		answered_questions = current_player.responses.map do |r|
			puts r.id
			puts r.option.inspect
			r.option.question_id
		end
		end
		@question = @artist.questions.where.not(id: answered_questions).order('id asc').take
		redirect_to category_path(@artist.category) if @question.nil?
		flash[:alert] = "Congrats! You've correctly answered all current questions for this artist. Please choose another!" if @question.nil?
	end

	def create
  	end

  	def artists
  	end

  	def contact
  	end

	def participant
	end

	# post '/responses' => 'artists#create_response', as: :response
	def create_response
		@response = Response.create(player_id: current_player.id, option_id: params[:option])
		@question = @response.option.question
		@total_questions = @question.artist.questions.count
		@answered = params[:correct].to_i
		if (@response.option.correct) && (@answered < @total_questions) 
			@answered += 1
			redirect_to category_artist_path(last_question: @question.id, correct: @answered,
			category_id: @question.artist.category.id, id: @question.artist.id)
		elsif @response.option.correct
			redirect_to category_path(@question.artist.category)
		else
			artist = @response.option.question.artist
			redirect_to category_path(artist.category), notice: "Sorry try again!"
		end
	end

	def edit
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_player!

	def index
		@question = Question.take
		@players = Player.all
	end

	def new
		@question = Question.order("RANDOM()").first
	end

	def edit
	end
end

app/controllers/fact_controller.rb
class FactController < ApplicationController
	before_filter :authenticate_player!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if player_signed_in?
			redirect_to :controller=> 'dashboard', :action => 'index'	
		end
	end

	def index2
	end

	def show
	end

	def new
	end

	def index
	end
end

app/controllers/option_controller.rb
class OptionController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@option = Option.new
	end

	def index
		@option = Option.all
	end

	def edit
	end

	def show
		@option = Option.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fact_helper.rb
module FactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/playerquestions_helper.rb
module PlayerquestionsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/dashboard/index.html.erb
<!-- Displays a leaderboard for Players -->
<section class="home-content">
	<div class="leader_board">
		<h1>Leaderboard</h1>
		<h5>Find out how you stack up against your friends</h5>
	</div>

  

	<div class="panel panel-default table-responsive" style="width:75%">
		<table class="table center-table table-bordered table-hover" style="width:75%">
			<thead>
				<tr>
					<th>Player</th>
					<th>Score</th>
				</tr>
			</thead>
			<tbody>
				<% @players.each do |player| %> 
				<tr>
					<td><%= player.email %></td> 
					<td><%= player.points %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>


	<div class="start">
		<%= button_to 'Start Game', categories_path, :id => "open-contacts-dialog-btn",
	:class => "button", :method => :get %>

	</div>
</section> 

app/views/home/index.html.erb
<section class="front_page">

<div class="home_page">

  <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item">
          <img src="http://bootstrapbay.com/blog/wp-content/uploads/2014/05/imfree-singer_qzzm0j.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to MUSICscholar</h1>
              <p>The best free source of music fun on the web! </p>
            <%= button_to "Let's Play!", categories_path, :id => "open-contacts-dialog-btn",
  :class => "button", :method => :get %>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="https://farm8.staticflickr.com/7020/6577868753_a0b2811336_b.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Listen and Watch</h1>
              <p>Music videos featuring popular artists from your favorite genres.</p>
              <%= button_to "Let's Play!", categories_path, :id => "open-contacts-dialog-btn",
  :class => "button", :method => :get %>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="https://farm5.staticflickr.com/4127/5227928938_274c8cf8f4_b.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Rank It Up</h1>
              <p>Challenge your friends and make it to the top of the Leaderboard to become the ultimate music scholar!</p>
              <%= button_to "Let's Play!", categories_path, :id => "open-contacts-dialog-btn",
  :class => "button", :method => :get %>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->






      <!-- START THE FEATURETTES -->
<div class="container marketing">
      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"> Listen, Watch, Game. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">MUSICscholar brings together all of your favorite pastimes. You get to watch the music video of your favorite artists while challenging your friends on your musical knowledge.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://www.gratisography.com/pictures/182_1.jpg" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://www.gratisography.com/pictures/152_1.jpg" data-holder-rendered="true">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Discover New Videos Daily. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Oh yeah, it's that good. MUSICscholar curates its videos from YouTube's Vevo RSS feeds for the best quality music experience. Always stay on top of the latests music trends.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Opportunity for Artists. <span class="text-muted">Locals get to shine.</span></h2>
          <p class="lead">Get to know the musician next door. This is a future feature that will include quizes on local bands.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://lh4.ggpht.com/th89Oj8Ot2SGZkvl-aVUcGlyzhZcfy7Pliu4ncS8qLeKNZecxhzZHOH2PQW1Pr9qi-pya9gkxQlw0zclzQ=s620" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>© 2015 MUSICscholar, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>

    </div>
  </div>
</span>
     

app/views/home/index2.html.erb
<section class="front_page">

<div class="home_page">

  <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class=""></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item">
          <img src="http://bootstrapbay.com/blog/wp-content/uploads/2014/05/imfree-singer_qzzm0j.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Welcome to MUSICscholar</h1>
              <p>The best free source of music fun on the web! </p>
              <p><a class="button" href="#" role="button">Let's Play!</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="https://farm8.staticflickr.com/7020/6577868753_a0b2811336_b.jpg" alt="Second slide" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Listen and Watch</h1>
              <p>Music videos featuring popular artists from your favorite genres.</p>
              <p><a class="button" href="#" role="button">Let's Play!</a></p>
            </div>
          </div>
        </div>
        <div class="item active">
          <img src="https://farm5.staticflickr.com/4127/5227928938_274c8cf8f4_b.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Rank It Up</h1>
              <p>Challenge your friends and make it to the top of the Leaderboard to become the ultimate music scholar!</p>
              <p><a class="button" href="#" role="button">Let's Play!</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->






      <!-- START THE FEATURETTES -->
<div class="container marketing">
      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"> Listen, Watch, Game. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">MUSICscholar brings together all of your favorite pastimes. You get to watch the music video of your favorite artists while challenging your friends on your musical knowledge.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://www.gratisography.com/pictures/182_1.jpg" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://www.gratisography.com/pictures/169_1.jpg" data-holder-rendered="true">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Discover New Videos Daily. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Oh yeah, it's that good. MUSICscholar sources its videos from YouTube's Vevo RSS feeds for the best quality music experience. Always stay on top of the latests music trends.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Opportunity for Artists. <span class="text-muted">Locals get to shine.</span></h2>
          <p class="lead">Get to know the musician next door. This is a future feature that will include quizes on local bands.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" data-src="holder.js/500x500/auto" alt="500x500" src="http://www.gratisography.com/pictures/152_1.jpg" data-holder-rendered="true">
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>© 2015 MUSICscholar, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>

    </div>
  </div>
</section>
     

app/views/home/show.html.erb
<h1>Developer Team</h1>

app/views/player/index.html.erb
<h1>Contacts</h1>

app/views/player/show.html.erb
<h1>Contacts</h1>