config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  resources :dashboard
  resources :categories do
    resources :artists   do
      resources :questions do
        resources :responses do
        resources :options
      end
      end
    end
  end

  get '/categories' => 'categories#index'
  get '/artists' => 'artists#index'
  get 'index2' => 'home#index'
  get 'index23' => 'artists#index'
  post '/responses' => 'artists#create_response'
  root :to => 'home#index'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  rss_url     :string
#

class Artist < ActiveRecord::Base
	belongs_to :category
	has_many :questions, :dependent => :destroy
	has_many :facts
end

app/models/category.rb
	# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :artists
	has_many :questions, through: :artist
	has_many :facts, through: :artist
end

app/models/fact.rb
# == Schema Information
#
# Table name: facts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Fact < ActiveRecord::Base
	belongs_to :artist
end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  text        :string
#  correct     :boolean
#  question_id :integer
#

class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Player < ActiveRecord::Base
	has_many :responses
	has_many :player_questions
	has_many :questions, through: :player_questions
	# has_many :points

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         def points
          # refactor into single query without map

          # go to responses datatable, return me responses where 
          ## the player is the same player this method is being used on
          # => [<response><response>]
          Response.where(player: self).map{ |response|
            if response.option.correct
              response
            else
              nil
            end
          }.compact.count
          # => [nil, <response>, <response>, nil, <response>].compact
          # => [<response>, <response>, <response>].count
          # => 3
         end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#  text       :string
#  youtube_id :string
#

class Question < ActiveRecord::Base
	has_many :options, :dependent => :destroy
	belongs_to :artist
	belongs_to :category
	has_many :responses, through: :options
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  player_id  :integer
#  option_id  :integer
#

class Response < ActiveRecord::Base
	belongs_to :player
	belongs_to :option
	belongs_to :question
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@artist = Artist.new
	end

	def index
		@artist = Artist.all
	end

	def index23
	end

	def show
		@artist = Artist.find(params[:id])
		if current_player
		answered_questions = current_player.responses.map do |r|
			puts r.id
			puts r.option.inspect
			r.option.question_id
		end
		end
		@question = @artist.questions.where.not(id: answered_questions).order('id asc').take
		redirect_to category_path(@artist.category) if @question.nil?
		flash[:alert] = "Congrats! You've correctly answered all current questions for this artist. Please choose another!" if @question.nil?
	end

	def create
  	end

  	def artists
  	end

  	def contact
  	end

	def participant
	end

	# post '/responses' => 'artists#create_response', as: :response
	def create_response
		@response = Response.create(player_id: current_player.id, option_id: params[:option])
		@question = @response.option.question
		@total_questions = @question.artist.questions.count
		@answered = params[:correct].to_i
		if (@response.option.correct) && (@answered < @total_questions) 
			@answered += 1
			redirect_to category_artist_path(last_question: @question.id, correct: @answered,
			category_id: @question.artist.category.id, id: @question.artist.id)
		elsif @response.option.correct
			redirect_to category_path(@question.artist.category)
		else
			artist = @response.option.question.artist
			redirect_to category_path(artist.category), notice: "Sorry try again!"
		end
	end

	def edit
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_player!

	def index
		@question = Question.take
		@players = Player.all
	end

	def new
		@question = Question.order("RANDOM()").first
	end

	def edit
	end
end

app/controllers/fact_controller.rb
class FactController < ApplicationController
	before_filter :authenticate_player!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if player_signed_in?
			redirect_to :controller=> 'dashboard', :action => 'index'	
		end
	end

	def index2
	end

	def show
	end

	def new
	end

	def index
	end
end

app/controllers/option_controller.rb
class OptionController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@option = Option.new
	end

	def index
		@option = Option.all
	end

	def edit
	end

	def show
		@option = Option.find(params[:id])
	end
	
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :authenticate_player!
	def index
	end

	def new
	end

	def edit
	end

	def artist_question
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fact_helper.rb
module FactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/playerquestions_helper.rb
module PlayerquestionsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/artists/index.html.erb
<div class ="developer">
<div class="container marketing">
<h1>Developer Team</h1>


<div class="row">
	
        <div class="col-lg-5">
          <img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/8/005/09a/3e8/182ad00.jpg" alt="Enide Dufresne" style="width: 200px; height: 200px;">
          <h2>Enide Dufresne</h2>
          <p>"Code is what I do!"</p>
          <p>786.389.6149</p>
          <p><a href="mailto:enide.dufresne@gmail.com">enide.dufresne@gmail.com</a></p>
          <p><a class="btn btn-default" href="https://github.com/enidedufresne?tab=repositories" role="button">Git Hub</a></p>
          <p><a class="btn btn-default" href="https://www.linkedin.com/profile/view?id=14576249&trk=nav_responsive_tab_profile" role="button">LinkedIn</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-sm-2"></div>
        <div class="col-lg-5">
          <img class="img-circle" src="https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAANKAAAAJDc2NzhkZTMzLTc4OTQtNDc2Zi1iOTkxLWZjOTg2MzE2YjA2NQ.jpg" alt="Alex Moraleza" style="width: 200px; height: 200px;">
          <h2>Alex Moraleza</h2>
          <p>"I love Ruby on Rails."</p>
          <p>305.498.5411</p>
          <p><a href="mailto:alexanderbusta@hotmail.com">AMoraleza@outlook.com</a></p>
          <p><a class="btn btn-default" href="https://github.com/AMoraleza?tab=repositories" role="button">Git Hub</a></p>
          <p><a class="btn btn-default" href="https://www.linkedin.com/profile/view?id=355346899&authType=name&authToken=KwzR&trk=hp-props-feed-member-name&sl=NPU_PC%3B14576249-1426110914431-826bb4d6a31dd9c72a466e4591f2af68%3B-1%3Bactivity%3A5981237922106527744%3B10%3B0%3B" role="button">LinkedIn</a></p>
        </div><!-- /.col-lg-4 -->
</div>

<div class="row">
	<div class="col-sm-4"><br><p>              </p><br><p>              </p></div>
</div>

	<h3>Special Thanks!</h3>
	<div class="col-sm-4"></div>
	 <div class="col-lg-4">
          <img class="img-circle" src="https://course_report_production.s3.amazonaws.com/rich/rich_files/rich_files/117/s300/wyncode-logo.jpeg" alt="Wyncode" style="width: 140px; height: 140px;">
          <h5>To all of the members of the Wyncode Administration and Teaching Team</h5>
          <p>We could not have accomplished all of this wonderful code without your support. Thank you!</p>
        </div><!-- /.col-lg-4 -->
      </div>
     <div class="col-sm-4"></div>
</div>

app/views/artists/show.html.erb
<div class="question">
  <h3 class="question_text">
  <%= @question.text %></h3>

	
  <div id="player"></div>
  <%= javascript_include_tag 'https://www.youtube.com/iframe_api' %>
  <% if @question.youtube_id %>
	<%= javascript_tag do %> 

onYouTubeIframeAPIReady = function() {
	console.log("iframe is ready");
	player = new YT.Player('player', {
          height: '360',
          width: '640',
          videoId: '<%= @question.youtube_id %>', 
          playerVars: { 'autoplay': 1, 
                        'start': 20, 
                        'end': 50, 
                        'theme': 'dark',
                        'disablekb': 1,
                        'controls': 0,
                        'autohide': 1,

                        'fs': 0, 
                        'iv_load_policy': 3, 
                        'modestbranding': 1, 
                        'rel': 0, 
                        'showinfo': 0},
        }
    );
}
<% end %>
<% end %>
	
  <% @question.options.shuffle.each do |option| %>
		<div class="col-md-6 col-md-6">
      <div class="option_thumbnail">
			<h4><%= link_to option.text, responses_path(option: option.id, correct: params[:correct]), method: :post  %></h4>
      </div>
		</div > <!-- nav nav-pills nav-stacked -->
	<% end %>
</div> <!-- question -->

app/views/questions/index2.html.erb
<h1>Reggae Quiz</h1>
<p>Which Reggae artist made the song "No Woman No Cry?</p>

app/views/questions/index3.html.erb
<h1>R&B Quiz</h1>
<p>Which R&B artist is currently married to Hip-Hop artist Jay-Z?</p>