config/routes.rb
Rails.application.routes.draw do
  devise_for :players
  resources :dashboard
  resources :categories do
    resources :artists   do
      resources :questions do
        resources :responses do
        resources :options
      end
      end
    end
  end

  get '/categories' => 'categories#index'
  get '/artists' => 'artists#index'
  get 'index2' => 'home#index'
  get 'index23' => 'artists#index'
  post '/responses' => 'artists#create_response'
  root :to => 'home#index'

end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  rss_url     :string
#

class Artist < ActiveRecord::Base
	belongs_to :category
	has_many :questions, :dependent => :destroy
	has_many :facts
end

app/models/category.rb
	# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ActiveRecord::Base
	has_many :artists
	has_many :questions, through: :artist
	has_many :facts, through: :artist
end

app/models/fact.rb
# == Schema Information
#
# Table name: facts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Fact < ActiveRecord::Base
	belongs_to :artist
end

app/models/option.rb
# == Schema Information
#
# Table name: options
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  text        :string
#  correct     :boolean
#  question_id :integer
#

class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Player < ActiveRecord::Base
	has_many :responses
	has_many :player_questions
	has_many :questions, through: :player_questions
	# has_many :points

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :confirmable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         def points
          # refactor into single query without map

          # go to responses datatable, return me responses where 
          ## the player is the same player this method is being used on
          # => [<response><response>]
          Response.where(player: self).map{ |response|
            if response.option.correct
              response
            else
              nil
            end
          }.compact.count
          # => [nil, <response>, <response>, nil, <response>].compact
          # => [<response>, <response>, <response>].count
          # => 3
         end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#  text       :string
#  youtube_id :string
#

class Question < ActiveRecord::Base
	has_many :options, :dependent => :destroy
	belongs_to :artist
	belongs_to :category
	has_many :responses, through: :options
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  player_id  :integer
#  option_id  :integer
#

class Response < ActiveRecord::Base
	belongs_to :player
	belongs_to :option
	belongs_to :question
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@artist = Artist.new
	end

	def index
		@artist = Artist.all
	end

	def index23
	end

	def show
		@artist = Artist.find(params[:id])
		if current_player
		answered_questions = current_player.responses.map do |r|
			puts r.id
			puts r.option.inspect
			r.option.question_id
		end
		end
		@question = @artist.questions.where.not(id: answered_questions).order('id asc').take
		redirect_to category_path(@artist.category) if @question.nil?
		flash[:alert] = "Congrats! You've correctly answered all current questions for this artist. Please choose another!" if @question.nil?
	end

	def create
  	end

  	def artists
  	end

  	def contact
  	end

	def participant
	end

	# post '/responses' => 'artists#create_response', as: :response
	def create_response
		@response = Response.create(player_id: current_player.id, option_id: params[:option])
		@question = @response.option.question
		@total_questions = @question.artist.questions.count
		@answered = params[:correct].to_i
		if (@response.option.correct) && (@answered < @total_questions) 
			@answered += 1
			redirect_to category_artist_path(last_question: @question.id, correct: @answered,
			category_id: @question.artist.category.id, id: @question.artist.id)
		elsif @response.option.correct
			redirect_to category_path(@question.artist.category)
		else
			artist = @response.option.question.artist
			redirect_to category_path(artist.category), notice: "Sorry try again!"
		end
	end

	def edit
	end
end

app/controllers/fact_controller.rb
class FactController < ApplicationController
	before_filter :authenticate_player!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if player_signed_in?
			redirect_to :controller=> 'dashboard', :action => 'index'	
		end
	end

	def index2
	end

	def show
	end

	def new
	end

	def index
	end
end

app/controllers/option_controller.rb
class OptionController < ApplicationController
	before_filter :authenticate_player!
	
	def new
		@option = Option.new
	end

	def index
		@option = Option.all
	end

	def edit
	end

	def show
		@option = Option.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/fact_helper.rb
module FactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/option_helper.rb
module OptionHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

  <title>Music Scholar:BETA</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">MUSICscholar</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'Home', index2_path %></li>
                <li class="dropdown">
                  <a href="http://www.musicscholar.co/categories?" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Games <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="http://www.musicscholar.co/categories?">Genres</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Coming Soon!</li>
                    <li><a href="#">Local Artists</a></li>
                    <li><a href="#">Favorites</a></li>
                    <li><a href="#">Challenges</a></li>
                  </ul>
                </li>
                <li><%= link_to 'Leaderboard', dashboard_index_path %></li>
                <li><%= link_to 'Contact', index23_path %></li>
                <li class="current_points"><p>Your Score: <%= current_player.points rescue nil %></li>
              </ul>

              <div class="player_nav">
                <% if player_signed_in? %>
                  Signed in as <strong><%= current_player.email %></strong>.
                  Not you?|
                  <%= link_to "Log Out", destroy_player_session_path, :method => :delete %>
                <% else %>
                  <%= link_to "Sign Up", new_player_registration_path %> or <%= link_to "Log In", new_player_session_path %>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </div>

    

<div class="devise_alert">
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</div>

<%= yield %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

  <title>Music Scholar:BETA</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>input{ color: #333; background-color: #FFF }</style>
</head>
<body>

<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">MUSICscholar</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><%= link_to 'Home', index2_path %></li>
                <li class="dropdown">
                  <a href="http://www.musicscholar.co/categories?" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Games <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="http://www.musicscholar.co/categories?">Genres</a></li>
                    <li class="dropdown-header">Coming Soon!</li>
                    <li><a href="#">Local Artists</a></li>
                    <li><a href="#">Favorites</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Challenges</a></li>
                  </ul>
                </li>
                <li><%= link_to 'Leaderboard', dashboard_index_path %></li>
                <li><%= link_to 'Contact', index23_path %></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>


<div class="devise_alert">
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
</div>

<div class="devise">
<%= yield %>
</div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

</body>
</html>